class StorageKeys {
  static const LOCATION_DATA = 'LOCATION_DATA';
  static const CONTACT_DATA = 'CONTACT_DATA';
  static const PARTICIPATE = 'PARTICIPATE';
  static const MY_UUIDs = 'MY_UUIDs';
  static const CROSSED_PATHS = 'CROSSED_PATHS';
  static const LANG_OVERRIDE = 'LANG_OVERRIDE';
  static const DEBUG_MODE = 'DEBUG_MODE';
  static const AUTHORITY_NEWS = 'AUTHORITY_NEWS';
  static const LAST_CHECKED = 'LAST_CHECKED';
  static const AUTHORITY_SOURCE_SETTINGS = 'AUTHORITY_SOURCE_SETTINGS';
  static const ENABLE_HCA_AUTO_SUBSCRIPTION = 'ENABLE_HCA_AUTO_SUBSCRIPTION';
  static const FEATURE_FLAG_VALS = 'FEATURE_FLAG_VALS';
  static const ONBOARDING_DONE = 'ONBOARDING_DONE';
}
